ALTER TABLE "GiftItem" ADD COLUMN "originalPrice" DOUBLE PRECISION;
ALTER TABLE "GiftItem" ADD COLUMN "currentPrice" DOUBLE PRECISION;
ALTER TABLE "GiftItem" ADD COLUMN "shippingCost" DOUBLE PRECISION;
ALTER TABLE "GiftItem" ADD COLUMN "estimatedTotalCost" DOUBLE PRECISION;
ALTER TABLE "GiftItem" ADD COLUMN "priceSourceUrl" TEXT;
ALTER TABLE "GiftItem" ADD COLUMN "bestFoundPrice" DOUBLE PRECISION;
ALTER TABLE "GiftItem" ADD COLUMN "bestFoundTotalCost" DOUBLE PRECISION;
ALTER TABLE "GiftItem" ADD COLUMN "bestFoundStoreName" TEXT;
ALTER TABLE "GiftItem" ADD COLUMN "priceLastCheckedAt" TIMESTAMP(3);
